### ISSUE TITLE
When gift_message_text contains a < character, value for extra field in lengow_orders it's badly saved (cut at that character).

### ISSUE THREAD

**Issue by josecarlosphp** [lengow/plugin-prestashop#7]
Sometimes someone add a gift message for his/her order, for example: "Love you <3".
It can be done in Amazon and other marketplaces as well.

That gift message it's included in order data from Lengow, as _gift_message_text_.
When importing order from Lengow into PrestaShop, full order data in json format is saved in _extra_ field from _lengow_orders_ table.

But when gift message contains a "<" character, the json value is badly saved.
It's cut at that character position.
Following the example, the value saved will be cut, ending with "Love you ".

This is a big trouble when you need to review original data (corresponding to when the order was imported into PrestaShop).
The json value turns unloadable (it fails _json_decode_), and all data since gift message is lost.

Maybe "<" is not the only character that can cause this problem.

**Comment by alherlengow** [comment]
hi it's fixed in 3.5.7 plugin version

**Comment by josecarlosphp** [comment]
Yes, it's fixed in 3.5.7 version, thank you.
